# ??? ????
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/asianadb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 1000
        format_sql: true
        show_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

logging:
  level:
    root: info
    org:
      hibernate: info
